version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 512
  services:
    rabbit-api-dev:
      mem_limit: 0.3GB
      cpu_shares: 300