version: "3"
services:
  rabbit-cron-dev:
    image: __ECR_ADDRESS__
    ports:
      - "5000:5000"
    entrypoint: /usr/local/bin/poetry
    command: "run flask start-worker rabbit.notification.keyword.v1"
    logging:
      driver: awslogs
      options:
        awslogs-group: bium/rabbit-cron-dev-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: bium/rabbit-cron-dev-logs
        awslogs-create-group: "true"
    environment:
      # environment