version: "3"
services:
  rabbit-api-dev:
    image: 384944374478.dkr.ecr.ap-northeast-2.amazonaws.com/rabbit-api-dev:13
    ports:
      - "0:5000"
    entrypoint: /usr/local/bin/poetry
    command: "run newrelic-admin run-program gunicorn -w 2 -b :5000 --access-logfile - --error-logfile - application:app"