version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    cpu_limit: 450
    mem_limit: 0.4GB
  services:
    rabbit-api-dev:
      cpu_shares: 300
      mem_limit: 0.3GB
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-06537409c97e597d0"
        - "subnet-0feceef9f1f22855c"
      security_groups:
        - "sg-051e1efcd57b2a5f3"
      assign_public_ip: DISABLED