version: "3"
services:
  rabbit-api-dev:
    image: __ECR_ADDRESS__
    ports:
      - "5000:5000"
    entrypoint: /usr/local/bin/poetry
    command: "run gunicorn -k gevent application:app --bind 0.0.0.0:5000 --reload --log-level=DEBUG"
    logging:
      driver: awslogs
      options:
        # FIX : Change log group
        awslogs-group: bium/rabbit-api-dev-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: bium/rabbit-api-dev-logs
        awslogs-create-group: "true"
    environment:
    # Environment