openapi: "3.0.2"
tags:
  - Post
security:
  - userAuth: []
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          user_id:
            type: integer
          title:
            type: string
          body:
            type: string
          region_group_id:
            type: integer
          type:
            type: string
          is_comment_disabled:
            type: boolean
          is_deleted:
            type: boolean
          is_blocked:
            type: boolean
          report_count:
            type: integer
          read_count:
            type: integer
          category:
            type: integer
responses:
  '200':
    description: A post object
    content:
      application/json:
        schema:
          type: object
          properties:
            id:
              type: integer
            user_id:
              type: integer
            title:
              type: string
            body:
              type: string
            region_group_id:
              type: integer
            type:
              type: string
            is_comment_disabled:
              type: boolean
            is_deleted:
              type: boolean
            is_blocked:
              type: boolean
            report_count:
              type: integer
            read_count:
              type: integer
            category:
              type: integer
            last_user_action:
              type: string
            last_user_action_at:
              type: string
            last_admin_action:
              type: string
            last_admin_action_at:
              type: string
            created_at:
              type: string
            updated_at:
              type: string
            user:
              $ref: '#/components/schemas/user'
  '400':
    description: unauthorized_error, invalid_request_error, not_found_error
    content:
      application/json:
        schema:
          type: object
          properties:
            error_message:
              type: string
              example: ""
            type:
              type: string
              example: unauthorized_error
