openapi: "3.0.2"
tags:
  - Post
security:
  - userAuth: []
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          user_id:
            type: integer
          title:
            type: string
          body:
            type: string
          region_group_id:
            type: integer
          type:
            type: string
          is_comment_disabled:
            type: boolean
          is_deleted:
            type: boolean
          is_blocked:
            type: boolean
          report_count:
            type: integer
          read_count:
            type: integer
          category_ids:
            type: array
            items:
              type: integer
responses:
  '200':
    description: create post
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/post'
  '400':
    description: unauthorized_error, invalid_request_error, not_found_error, system_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/error'