openapi: "3.0.2"
tags:
  - Post
security:
  - userAuth: []
parameters:
  - name: post_id
    in: path
    required: true
    schema:
      type: int
responses:
  '200':
    description: delete post
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/post'
  '400':
    description: unauthorized_error, invalid_request_error, not_found_error, system_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/error'
