openapi: "3.0.2"
tags:
  - Post
security:
  - userAuth: []
requestBody:
  content:
    application/json:
      schema:
        type: object
        properties:
          user_id:
            type: integer
          previous_post_id:
            type: integer
responses:
  '200':
    description: get like post list
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              items:
                $ref: '#/components/schemas/post'
            meta:
              $ref: '#/components/schemas/post_meta'
  '400':
    description: unauthorized_error, invalid_request_error, system_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/error'
