openapi: "3.0.2"
tags:
  - Post
security:
  - userAuth: []
parameters:
  - in: path
    name: post_id
    required: true
    schema:
      type: integer
requestBody:
  required: true
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          user_id:
            type: integer
          title:
            type: string
          body:
            type: string
          region_group_id:
            type: integer
          type:
            type: string
          is_comment_disabled:
            type: boolean
          category_ids:
            type: array
            items:
              type: integer
          file_type:
            type: string
          files:
            type: array
responses:
  '200':
    description: update post
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/post'
  '400':
    description: unauthorized_error, invalid_request_error, not_found_error, system_error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/error'
